#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScoreMore.Resource", IsApplication=true)]

namespace ScoreMore
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ScoreMoreLib.Resource.String.library_name = global::ScoreMore.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int but_registreren = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int button1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int button2 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int button3 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int button4 = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int editText1 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int editText2 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int editText3 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int editText4 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int editText5 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int editText6 = 2131034141;
			
			// aapt resource value: 0x7f05000d
			public const int her_wachtwoord = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int inv_email = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int inv_wachtwoord = 2131034123;
			
			// aapt resource value: 0x7f05001e
			public const int linearLayout1 = 2131034142;
			
			// aapt resource value: 0x7f050001
			public const int listview1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int menu_groepen = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int menu_panel = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int menu_training = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int menu_vraag = 2131034115;
			
			// aapt resource value: 0x7f050020
			public const int multipel = 2131034144;
			
			// aapt resource value: 0x7f050000
			public const int naarSubsButton = 2131034112;
			
			// aapt resource value: 0x7f050016
			public const int relativeLayout1 = 2131034134;
			
			// aapt resource value: 0x7f05001f
			public const int singulier = 2131034143;
			
			// aapt resource value: 0x7f050010
			public const int textView1 = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int textView2 = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int textView3 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int textView4 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int textView5 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int textView6 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int textView7 = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int txt_waarschuwing = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int volgendebutton = 2131034133;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MaakTraining = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int registreren = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int trainingFeedback = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VolgendeLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Vraag1Layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Vraaginvoer1 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Vraaginvoer2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int VraagInvoerMain = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int menu_groepen = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int menu_panel = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int menu_training = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menu_vraag = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int volgende = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
