#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
//     Runtime Version:4.0.30319.34209
=======
//     Runtime Version:4.0.30319.34014
>>>>>>> origin/master
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScoreMore.Resource", IsApplication=true)]

namespace ScoreMore
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ScoreMoreLib.Resource.String.library_name = global::ScoreMore.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int onderwerp_lijst = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int subonderwerp_lijst = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001f
			public const int antwoord = 2131099679;
			
			// aapt resource value: 0x7f060026
			public const int antwoord2 = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int but_hoofdmenu = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int but_registreren = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int button1 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int button2 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int button3 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int button4 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int editText1 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int editText2 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int editText3 = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int editText4 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int editText5 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int editText6 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int goede_antwoord2 = 2131099685;
			
			// aapt resource value: 0x7f060011
			public const int her_wachtwoord = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int inv_email = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int inv_wachtwoord = 2131099663;
			
			// aapt resource value: 0x7f060028
			public const int linearLayout1 = 2131099688;
			
			// aapt resource value: 0x7f060015
			public const int listView1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int listView2 = 2131099670;
			
			// aapt resource value: 0x7f060001
			public const int listview1 = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int login_naam = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int menu_feedback = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int menu_groepen = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int menu_mijntrainingen = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int menu_panel = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int menu_training = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int menu_vraag = 2131099652;
			
			// aapt resource value: 0x7f06002a
			public const int multipel = 2131099690;
			
			// aapt resource value: 0x7f060000
			public const int naarSubsButton = 2131099648;
			
			// aapt resource value: 0x7f06002b
			public const int open = 2131099691;
			
			// aapt resource value: 0x7f06001c
			public const int relativeLayout1 = 2131099676;
			
			// aapt resource value: 0x7f060029
			public const int singulier = 2131099689;
			
			// aapt resource value: 0x7f06002c
			public const int spinner = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int spinner1 = 2131099693;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int textView2 = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int textView3 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int textView4 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int textView5 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int textView6 = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int textView7 = 2131099662;
			
			// aapt resource value: 0x7f060021
			public const int toevoegen = 2131099681;
			
			// aapt resource value: 0x7f060027
			public const int toevoegen2 = 2131099687;
			
			// aapt resource value: 0x7f060013
			public const int txt_waarschuwing = 2131099667;
			
			// aapt resource value: 0x7f060030
			public const int vraaghoofdmenu = 2131099696;
			
			// aapt resource value: 0x7f06002e
			public const int vraaginvoervolgende = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int vraagreturn = 2131099695;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MaakTraining = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainMenu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int registreren = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int trainingFeedback = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VolgendeLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Vraag1Layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Vraaginvoer1 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Vraaginvoer2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int VraagInvoerMain = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int vraaginvoerOnderwerpkeuze = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int VraaginvoerSlot = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int Onderwerp = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Subonderwerp = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int menu_groepen = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int menu_panel = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int menu_training = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menu_vraag = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int volgende = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
